Add Stein lab
oicr-gsi/miso-lims pull request #120
Opened 2016-11-18 19:29 UTC by apmasell

2016-11-18 19:29 UTC, tonydebat commented
Can one of the admins verify this patch?

2016-11-18 19:32 UTC, callunity requested changes
Could you change the file name to an 8800-series name, as per https://documentation.tgac.ac.uk/pages/viewpage.action?pageId=10420525 ? Tony has the 8000-series and this could conflict if he writes a migration.

2016-11-21 16:22 UTC, apmasell commented
Fixed.

2016-11-21 16:32 UTC, tonydebat approved these changes

2016-11-21 16:36 UTC, callunity approved these changes

2016-11-21 17:16 UTC, merged