Add special indicies for PFE project
oicr-gsi/miso-lims pull request #122
Opened 2016-11-24 15:51 UTC by apmasell

JIRA: GLT-910

2016-11-24 15:51 UTC, tonydebat commented
Can one of the admins verify this patch?

2016-11-24 16:04 UTC, callunity requested changes
Please wrap this in `NoTest`.

2016-11-24 16:25 UTC, callunity approved these changes

2016-11-29 14:44 UTC, tonydebat approved these changes

2016-11-29 16:00 UTC, merged