Add thymus tissue type
oicr-gsi/miso-lims pull request #124
Opened 2016-11-24 20:50 UTC by apmasell

JIRA: GC-764

2016-11-24 20:50 UTC, tonydebat commented
Can one of the admins verify this patch?

2016-11-24 21:25 UTC, callunity approved these changes

2016-11-28 18:06 UTC, callunity requested changes
Please wrap this in NoTest, as tests are failing.

2016-11-28 18:35 UTC, apmasell commented
Fixed.

2016-11-28 19:48 UTC, callunity approved these changes

2016-11-29 14:48 UTC, tonydebat approved these changes

2016-11-29 15:57 UTC, merged