GLT-1390 harmonize TGL kits and tarseqs
oicr-gsi/miso-lims pull request #138
Opened 2017-01-04 20:31 UTC by callunity

Once approved, this migration will be run before the next release.

2017-01-04 21:01 UTC, djcooke requested changes

2017-01-04 21:01 UTC, djcooke commented on sqlstore/src/main/resources/db/migration/V8251__harmonize_TGL_kd_ts.sql
> +UPDATE KitDescriptor SET name = 'Agilent SureSelect XT Human All Exon V6 Cosmic' WHERE name = 'Agilent SureSelect Human All Exon V6 Cosmic';
Kit 'Agilent SureSelect Human All Exon V6 Cosmic' exists in GSLE, so if it is renamed, there will be issues with Pinery-MISO migration, and a mismatch between GSLE data pre migration and MISO data post migration

2017-01-04 21:01 UTC, djcooke commented on sqlstore/src/main/resources/db/migration/V8251__harmonize_TGL_kd_ts.sql
> +    WHERE libraryId = (SELECT library_libraryId FROM LibraryDilution WHERE targetedSequencingId IN (SELECT targetedSequencingId FROM TargetedSequencing
Should this be `WHERE libraryId IN...`?

2017-01-04 21:01 UTC, djcooke commented on sqlstore/src/main/resources/db/migration/V8251__harmonize_TGL_kd_ts.sql
> +CREATE PROCEDURE updateLibraryKitsIfTarSeqUpdated()
Procedure and IF statements are unnecessary since the update queries will do nothing in cases where the IF condition is false

2017-01-04 21:30 UTC, callunity commented on sqlstore/src/main/resources/db/migration/V8251__harmonize_TGL_kd_ts.sql
> +    WHERE libraryId = (SELECT library_libraryId FROM LibraryDilution WHERE targetedSequencingId IN (SELECT targetedSequencingId FROM TargetedSequencing
Yes

2017-01-04 21:30 UTC, callunity commented on sqlstore/src/main/resources/db/migration/V8251__harmonize_TGL_kd_ts.sql
> +CREATE PROCEDURE updateLibraryKitsIfTarSeqUpdated()
Point.

2017-01-04 21:31 UTC, callunity commented on sqlstore/src/main/resources/db/migration/V8251__harmonize_TGL_kd_ts.sql
> +UPDATE KitDescriptor SET name = 'Agilent SureSelect XT Human All Exon V6 Cosmic' WHERE name = 'Agilent SureSelect Human All Exon V6 Cosmic';
I'm in conversation with Dax, Mike, and Tony about this, and am looking into what is required to change the name of the kit and targeted resequencing in GSLE.

2017-01-05 14:58 UTC, callunity commented
Updated to remove "XT" from the name.

2017-01-05 15:43 UTC, djcooke approved these changes

2017-01-05 16:10 UTC, apmasell approved these changes

2017-01-05 16:21 UTC, merged