Add nano and micro MiSeq flowcells
oicr-gsi/miso-lims pull request #155
Opened 2017-03-13 15:21 UTC by callunity

2017-03-13 15:49 UTC, apmasell approved these changes

2017-03-14 15:41 UTC, djcooke requested changes

2017-03-14 15:41 UTC, djcooke commented on sqlstore/src/main/resources/db/migration/V8261__miseq_nano_and_micro.sql
> +('Nano 2×151', @miseq, 'count(//RunInfoRead[@NumCycles=151]) = 2 and //FlowcellLayout[@TileCount=2]', 151, 1, @admin, CURRENT_TIMESTAMP, @admin, CURRENT_TIMESTAMP)
Missing comma at end of line

2017-03-14 15:52 UTC, callunity commented on sqlstore/src/main/resources/db/migration/V8261__miseq_nano_and_micro.sql
> +('Nano 2×151', @miseq, 'count(//RunInfoRead[@NumCycles=151]) = 2 and //FlowcellLayout[@TileCount=2]', 151, 1, @admin, CURRENT_TIMESTAMP, @admin, CURRENT_TIMESTAMP)
Thanks for catching that. Fixed now.

2017-03-14 16:08 UTC, djcooke approved these changes

2017-03-14 16:31 UTC, merged